language: android
jdk: oraclejdk8

env:
  - TERM=dumb

script:
  - ./gradlew build -x lint

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    tags: true
